import React from "react"
// import JSXBasics from "./components/BasicComponents/JSXBasics"
// import CreatingComponents from "./components/BasicComponents/CreatingComponents"
// import Props, { RenderChildFunc, ToDoListItemComponent, NameClass, ToDoListItemClass } from "./components/BasicComponents/Props"
// import UseStateHook, { Counter } from "./components/BasicStatefulComponents/UseStateHook"
// import StateInClassComponents, { CounterClass } from "./components/BasicStatefulComponents/StateInClassComponents"
// import InputEventListeners from "./components/BasicStatefulComponents/InputEventListeners"
// import ArrayStateProject from "./components/BasicStatefulComponents/ArrayStateProject"
// import CounterWithNameProject, { CounterWithNameClass } from "./components/BasicStatefulComponents/CounterWithNameProject"
// import VirtualDom from "./components/ComponentLifecycle/VirtualDom"
// import ComponentLifecycle from "./components/ComponentLifecycle/ComponentLifecycle"
// import UseEffectHook, { UseEffectExercise } from "./components/ComponentLifecycle/UseEffectHook"
// import ClassComponentLifecycleMethods from "./components/ComponentLifecycle/ClassComponentLifecycleMethods"
// import DataFetchFromAPI from "./components/ComponentLifecycle/DataFetchFromAPI"
// import ConditionalRendering from "./components/AdvancedComponents/ConditionalRendering"
// import RenderingLists from "./components/AdvancedComponents/RenderingLists"
// import Fragments from "./components/AdvancedComponents/Fragments"
// import UserListProject from "./components/AdvancedComponents/UserListProject"
// import RenderRawHTML from "./components/AdvancedComponents/RenderRawHTML"
// import HookRules from "./components/BasicHooks/HookRules"
// import UseRefHook from "./components/BasicHooks/UseRefHook"
// import RefsInClassComponents from "./components/BasicHooks/RefsInClassComponents"
// import UseMemoHook from "./components/BasicHooks/UseMemoHook"
// import UseCallbackHook from "./components/BasicHooks/UseCallbackHook"
// import CustomHooks from "./components/BasicHooks/CustomHooks"
// import UseFetchProject from "./components/BasicHooks/UseFetchProject"
// import UseArrayProject from "./components/BasicHooks/UseArrayProject"
// import UseLocalStorageProject from "./components/BasicHooks/UseLocalStorageProject"
// import FormBasics from "./components/Forms/FormBasics"
// import UseStateVsUseRef from "./components/Forms/UseStateVsUseRef"
// import BasicFormValidationProject from "./components/Forms/BasicFormValidationProject/BasicFormValidationProject"
// import ReactHookForm from "./components/Forms/ReactHookForm/ReactHookForm"
// import UseReducerHook, { UseFetchWithReducer } from "./components/AdvancedStatefulComponents/UseReducerHook"
// import UseContextHook from "./components/AdvancedStatefulComponents/UseContextHook"
// import NeverStoreDerivedState from "./components/AdvancedStatefulComponents/NeverStoreDerivedState"
// import EnvironmentVariables from "./components/AdvancedStatefulComponents/EnvironmentVariables"
// import AdvancedTodoListProject from "./components/AdvancedStatefulComponents/AdvancedTodoListProject/AdvancedTodoListProject"
// import RoutingWithoutALibrary from "./components/Routing/RoutingWithoutALibrary"
// import Portals from "./components/AdvancedReactConcepts/Portals/Portals"
// import ForwardRef from "./components/AdvancedReactConcepts/forwardRef/ForwardRef"
// import Modal from "./components/AdvancedReactConcepts/Modal/Modal"
// import AdvancedKeyUses from "./components/AdvancedReactConcepts/AdvancedKeyUses/AdvancedKeyUses"
// import CaptureEventListeners from "./components/AdvancedReactConcepts/CaptureEventListeners/CaptureEventListeners"
// import DatePickerProject from "./components/AdvancedReactConcepts/DatePicker/DatePicker"
// import UseLayoutEffect from "./components/AdvancedHooks/useLayoutEffect/UseLayoutEffect"
// import UseDebugValue from "./components/AdvancedHooks/useDebugValue/UseDebugValue"
// import UseId from "./components/AdvancedHooks/useId/UseId"
// import UseImperativeHandle from "./components/AdvancedHooks/useImperativeHandle/UseImperativeHandle"
// import UseCallbackAsRef from "./components/AdvancedHooks/useCallbackAsRef/UseCallbackAsRef"
import CSSModules from "./components/CSSAlternatives/CSSModules/CSSModules"
// import user from './user.json'
import './styles.css'
// import img from './img.jpg'

function App() {
  return (
    <CSSModules />
  )
}

export default App